import Control.Exception (assert)

main = assert False (putStrLn "OK")
