runghc: Uncaught exception ghc-internal:GHC.Internal.IO.Exception.IOException:

defer-type-errors: executeFile: does not exist (No such file or directory)

HasCallStack backtrace:
  ioError, called at libraries/ghc-internal/src/GHC/Internal/Foreign/C/Error.hs:428:5 in ghc-internal:GHC.Internal.Foreign.C.Error

